cha_bebe/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('sobre', views.sobre, name='sobre')
]

cha_bebe/galeria/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path
from . import views

app_name = 'galeria'
urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.album, name='album'),
    re_path(r'^imagem/(?P<slug>[\w_-]+)/$', views.imagem, name='imagem'),
]

cha_bebe/presente/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'presente'
urlpatterns = [
    path('', views.presente, name='presente'),
    re_path(r'^(?P<slug>[\w_-]+)/$', views.detalhe, name='detalhe'),
]

cha_bebe/recado/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'recado'
urlpatterns = [
    path('', views.recado, name='recado'),
    path('novo_recado', views.novo_recado, name='novo_recado'),
    path('salvo', views.salvo, name='salvo'),
]

cha_bebe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from .core import urls

urlpatterns = [
    path('',         include('cha_bebe.core.urls',     namespace="core")),
    path('galeria',  include('cha_bebe.galeria.urls',  namespace='galeria')),
    path('presente', include('cha_bebe.presente.urls', namespace='presente')),
    path('recado',   include('cha_bebe.recado.urls',   namespace='recado')),
    path('carrinho', include('cha_bebe.carrinho.urls', namespace='carrinho')),

    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cha_bebe/core/views.py
from django.shortcuts import render
import os
from django.conf import settings
from django.templatetags.static import static

def home(request):
	return render(request, 'home.html')

def sobre(request):
	return render(request, 'sobre.html')

cha_bebe/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="pt-br"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="pt-br"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="pt-br"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="pt-br">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<title>Chá de Bebê</title>
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="{% static 'stylesheets/foundation.min.css' %}">
<link rel="stylesheet" href="{% static 'stylesheets/main.css' %}">
<link rel="stylesheet" href="{% static 'stylesheets/app.css' %}">
<script src="{% static 'javascripts/modernizr.foundation.js' %}"></script>
<script src="http://code.jquery.com/jquery-1.7.1.js"></script>
<script src="{% static 'javascripts/blur/blur.min.js' %}"></script>

<!-- Google fonts -->
<link href='http://fonts.googleapis.com/css?family=Ranchers' rel='stylesheet' type='text/css'>
<!-- IE Fix for HTML5 Tags -->
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body>
<div class="row blur">
  <!-- page wrap -->
  <div class="twelve columns">
    <!-- page wrap -->
    <div class="row">
      <div class="nine columns" style="margin-bottom: 10px">
        <ul id="menu-header" class="nav-bar horizontal">
          <li><a href="{% url 'core:home' %}">Início</a></li>
          <li><a href="{% url 'core:sobre' %}">Sobre</a></li>
          <li> <a href="{% url 'presente:presente' %}">Presentes</a></li>
          <li><a href="{% url 'recado:recado' %}">Recados</a></li>
          <li ><a href="{% url 'galeria:index' %}">Galeria de fotos</a></li>
          </ul>
        <script>$('ul#menu-header').nav-bar();</script>
        <div style="clear:both"></div>
      </div>
      
    </div>
    <!-- end menu row (header) -->
    {% block content %}{% endblock %}

	

    

    <div class="row">

      <div class="twelve columns">
        <ul id="menu3" class="footer_menu horizontal">
          <li><span class="has-flyout">Copyright © 2020 <a href="https://josuealves.com/" target="_blank">Josué Alves Consultoria</a>. Todos os direitos reservados.</span></li>
        </ul>
      </div>
    </div>
    <script>$('ul#menu3').nav-bar();</script>
  </div>
</div>
<!-- end page wrap) -->
<!-- Included JS Files (Compressed) -->
<script src="{% static 'javascripts/foundation.min.js' %}"></script>
<!-- Initialize JS Plugins -->
<script src="{% static 'javascripts/app.js' %}"></script>
</body>
</html>

cha_bebe/core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="twelve columns">
            <div class="panel callout">
                <h1 class="heading_supersize">Bem vindo ao Chá de Bebê da Ester Alves</h1>
		        <h4 class="heading_text">texto introdutório</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="twelve columns">
            <div class="flex-video widescreen vimeo">
                <iframe src="https://www.youtube.com/embed/qXv1ImfILOs" width="900" height="350" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="four columns">
            <h3>Adipiscing Elit</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra, lacus id interdum ultrices, elit metus semper tellus, vel lacinia libero purus vitae risus. Integer a eros sit amet felis tincidunt commodo.</p>
            <a class="button round" href="#">More &raquo;</a>
        </div>
        <div class="four columns">
            <h3>Lectus Congue</h3>
            <p>Vivamus tortor tellus, rutrum sit amet mollis vel, imperdiet consectetur orci. Mauris pharetra congue enim, et sagittis lectus congue ut. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
            <a class="button round" href="#">More &raquo;</a>
        </div>
        <div class="four columns">
            <h3>Gravida Pharetra</h3>
            <p>Sed vitae nisi leo. Nulla tincidunt, turpis non gravida pharetra, diam sapien posuere massa, non luctus leo mauris at sapien. Donec ut fermentum eros. Vestibulum placerat dui sit amet quam.</p>
            <a class="button round" href="#">More &raquo;</a>
        </div>
    </div>

{% endblock %}

cha_bebe/core/templates/sobre.html
{% extends "base.html" %}

{% block content %}
    <h1>Sobre</h1>
{% endblock %}