cha_bebe/recado/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'recado'
urlpatterns = [
    path('', views.recado, name='recado'),
    path('novo_recado', views.novo_recado, name='novo_recado'),
    path('salvo', views.salvo, name='salvo'),
]

cha_bebe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
#from .core import urls

urlpatterns = [
    path('',         include('cha_bebe.core.urls',     namespace="core")),
    path('galeria',  include('cha_bebe.galeria.urls',  namespace='galeria')),
    path('presente', include('cha_bebe.presente.urls', namespace='presente')),
    path('recado',   include('cha_bebe.recado.urls',   namespace='recado')),
    path('carrinho', include('cha_bebe.carrinho.urls', namespace='carrinho')),

    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cha_bebe/recado/models.py
from django.db import models
from datetime import datetime

class Recado(models.Model):
    nome = models.CharField('Nome', max_length=50)
    sobrenome = models.CharField('Sobrenome', max_length=50)
    email = models.EmailField('E-mail')
    mensagem = models.TextField('Mensagem')
    aprovado = models.BooleanField(default=False)
    data_inclusao = models.DateTimeField(auto_now_add=True)

    @property
    def nome_completo(self):
        return '%s %s' % (self.nome, self.sobrenome)

cha_bebe/recado/forms.py
from django import forms
from .models import Recado
#from django.core.mail import send_mail
#from django.conf import settings

class FormRecado(forms.ModelForm):
    class Meta:
        model = Recado
        fields = ['nome', 'sobrenome', 'email', 'mensagem']

cha_bebe/recado/views.py
from django.shortcuts import render, redirect
from .models import Recado
from .forms import FormRecado

def recado(request):
    template_name = 'recados.html'
    recados = Recado.objects.filter(aprovado=True)

    context = {'recados': recados}
    return render(request, template_name, context)

def novo_recado(request):
    template_name = 'novo_recado.html'
    if request.method == 'POST':
        form = FormRecado(request.POST)
        if form.is_valid():
            form.save()
            return redirect('recado:salvo')

    else:
        form = FormRecado()
    context = {
        'form': form
    }
    return render(request, template_name, context)

def salvo(request):
    return render(request, 'salvo.html')

cha_bebe/recado/templates/novo_recado.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Deixe seu recado</h1>
    <div class="row">
        <div class="twelve columns">
            <div class="panel callout">
                <form action="{{ recado }}" class="forms-sample" method = 'POST' enctype="multipart/form-data">
                {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label><strong>{{ field.label_tag }}</strong></label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <button type="submit" class="button round">Enviar</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

cha_bebe/recado/templates/recados.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1>Recados</h1>
    <p>

        <a href="{% url 'recado:novo_recado'%}" class="button round">Incluir
            <i class="mdi mdi-file-check btn-icon-append"></i>
        </a>
    </p>

        {% for recado in recados %}
            <div class="box photo">
                <h4>{{ recado.nome_completo }}</h4>
                <p><h5> {{ recado.mensagem }} </h5></p>

            </div>

        {% endfor %}

{% endblock %}

cha_bebe/recado/templates/salvo.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="twelve columns">
            <div class="panel callout">
                <h1>Recado enviado com sucesso!</h1>
            </div>
        </div>
    </div>


{% endblock %}